### ISSUE TITLE
Latest release information is fragile

### ISSUE THREAD

**Issue by peabnuts123** [peabnuts123/npm-dep-analyser#1]
Depends on `.next()` too much, and will report a pile of blanks of one of the pieces of information next to the latest release informaton is absent. 

Each of `Last Published`, `Latest Version`, `GitHub` and `License` need to be independent

**Comment by ryankurte** [comment]
https://github.com/npm/npm-registry-client might help with querying the things ^_^

**Comment by peabnuts123** [comment]
Have considered using a package for mining this data. But wary of depending on too many packages haha

**Comment by ryankurte** [comment]
The irony. We can dogfood ^_^

**Comment by peabnuts123** [comment]
Have changed the way this works. Not fragile any more 👍
